AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  zillow-lambda

  Sample SAM Template for zillow-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120

Resources:
  ZillowCsvFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: zillow-lambda/
      Handler: app.lambda_handler
      Runtime: python3.9
      MemorySize: 1024
      Policies:
        - S3WritePolicy:
            BucketName: zillow-data-raw-staging
